### ISSUE TITLE
Navigate with query params

### ISSUE THREAD

**Issue by Bozonych** [udayvunnam/xng-breadcrumb#28]
When we use router with query param, bread crumbs module do not save these param. 
Maybe, can you add this feature to module?

**Comment by udayvunnam** [comment]
Sure! So, when you go back to the link by clicking breadcrumb, you would like to persist the query params? 

I will add this feature.

**Comment by Bozonych** [comment]
@udayvunnam that would be great. Waiting this. Thanks.

**Comment by mahmoudparandeh** [comment]
is there any progress on this feature? i have some issues when navigating routes like this:
{
    path: 'category/:category/:id',
    data:{breadcrumb:'محصولات'},
    children:[
      {
        path: '',
        component: ProductsPageComponent,
        pathMatch: 'full'
      },
      {
        path: 'detail/:id/:name',
        component: ProductPageComponent
      },
    ]
  },
when i go to route 'category/:category/:id/detail/:id/:name' and want to navigate back to product list with breadcrumb the path shows 'category/:category/:id' instead if something like 'catgeory/سبزیجات/1'

**Comment by mahmoudparandeh** [comment]
any update?

**Comment by elvir92** [comment]
any update or idea how to fix this ?

**Comment by udayvunnam** [comment]
In progress - @elvir92 @mahmoudparandeh. Will release in a week

**Comment by udayvunnam** [comment]
@Bozonych @mahmoudparandeh @elvir92 - This feature is available with xng-breadcrumb@5.1.0 onwards.

QueryParams and Fragment will be auto preserved while navigating via breadcrumbs

**Comment by mahmoudparandeh** [comment]
@udayvunnam it is good news i should update my app as soon as this update is available. thanks for you effort.

**Comment by mahmoudparandeh** [comment]
i test 5.1.0 but still not working with my scenario. it is not queryParam like &id=1&name=something, it is like this /1/something
here is my routing:
const routes: Routes = [
  {path:':category/:id',data:{breadcrumb:'محصولات'}, children:[
    {path: 'detail/:pid/:name', pathMatch:'full', component: ProductPageComponent},
    {path:'',pathMatch: 'full',component:ProductsPageComponent},
  ]},
  {path: 'detail/:pid/:name', pathMatch:'full', component: ProductPageComponent},
  {path: 'special', pathMatch:'full', component: SpecialProductsComponent, data:{breadcrumb:'محصولات ویژه'}},
  {path: 'offers', pathMatch:'full', component: OfferProductsComponent, data:{breadcrumb:'محصولات تخفیف‌دار'}},
  {path: 'search', component: SpecialProductsComponent, data:{breadcrumb:'جستجوی محصولات'}},
];
![breadcrumb](https://user-images.githubusercontent.com/36625602/84592632-669cd580-ae5c-11ea-9e3b-d176df1e1397.png)

**Comment by udayvunnam** [comment]
@mahmoudparandeh I have considered preserving query params with this issue. Can you create a minimal reproducible example with the issue you are facing?

To help you start with, I have create a Stackblitz example - https://stackblitz.com/edit/angular-xng-breadcrumbs. Please update and share the issue sample

**Comment by mahmoudparandeh** [comment]
sure i will notice you when i create small example.

**Comment by shray7** [comment]
Hey I've opened another issue with the sample reproducing the bug here: https://github.com/udayvunnam/xng-breadcrumb/issues/34

**Comment by udayvunnam** [comment]
This issue has been fixed with latest release xng-breadcrumb@6.0.0

**Comment by CelestialMusa** [comment]
I am currently on release xng-breadcrumb@6.7.0 and this issue is still there.


> This issue has been fixed with latest release xng-breadcrumb@6.0.0

**Comment by udayvunnam** [comment]
@CelestialMusa can you provide reproducible example with stackblitz.com
