### ISSUE TITLE
Empty breadcrumb at start

### ISSUE THREAD

**Issue by tiagotrigger** [udayvunnam/xng-breadcrumb#54]
This is started to happen in the latest version.
Version 6.2.1 is working.

![image](https://user-images.githubusercontent.com/3385597/99111435-e1fce180-25ca-11eb-8125-6edbcef204be.png)

https://i.imgur.com/hwZ62th.png

That first item should not be there.

**Comment by paulmhan** [comment]
![Screen Shot 2020-11-13 at 3 52 44 PM](https://user-images.githubusercontent.com/58451541/99131538-48343500-25c8-11eb-99cd-67eb42e9c5d5.png)

I am having a similar issue where a separator is showing before my first link, is there any way I can get rid of this?

**Comment by udayvunnam** [comment]
@tiagotrigger This is fixed in the latest version 6.3.3. Thanks for reporting the issue.

**Comment by tiagotrigger** [comment]
Hmm, that is weird, I've updated to 6.3.3 but still happens.

**Comment by udayvunnam** [comment]
@tiagotrigger This has been overlooked for another fix. The issue is fixed with **version 6.3.4** and also a test case is added to validate this.

**Comment by tiagotrigger** [comment]
Awesome, it is working now. Thank you very much.
